version: '3.8'

services:

  database:
    container_name: database-db
    image: mysql:8.0.35
    environment:
      - MYSQL_DATABASE=eous-db
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--user=root",  "--password=root", "--execute", "SHOW DATABASES;" ]
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile
    image: sufailbadushat/wish-backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/eous-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: always
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge




#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
